adjective = '''
aktuell (relevant, current)
alvorlig (serious)
ansvarlig (responsible)
berømt (famous)
betydelig (significant)
bevisst (conscious)
bred (broad, wide)
dum (stupid, silly)
dyp (deep)
ekkel (grose, disgusting)
eksisterende (existing)
ekte (real, genuine)
enkel (simple)
ensom (lonely)
falsk (false, fake)
fast (regular, fixed)
felles (common)
fersk (fresh, new)
fjern (remote, distant)
flau (embarrassed)
følsom (sensitive)
forsiktig (careful)
fremmed (foreign, strange)
fryktelig (terrible)
glatt (slippery)
gravid (pregnant)
grunnleggende (basic)
heldig (lucky)
hemmelig (secret)
hjelpsom (helpful)
hyppig (frequent)
imponerende (impressive)
kjedelig (boring)
kul (cool)
langsom (slow)
lat (lazy)
lav (low)
lignende (similar)
løs (loose)
lovlig (legal)
lykkelig (happy)
lys (light)
menneskelig (human)
merkelig (odd, strange)
midlertidig (temporary)
mistenkelig (suspicious)
modig (brave)
mørk (dark)
morsom (funny)
motsatt (opposite)
mulig (possible)
naturlig (natural)
nåværende (present, current)
nødvendig (necessary)
nøyaktig (accurate)
nysgjerrig (curious)
nyttig (useful)
offentlig (public)
opprinnelig (original)
ordentlig (decent)
plutselig (sudden)
rå (raw)
rask (quick)
regelmessig (regular)
ren (clean)
rettferdig (fair)
rimelig (reasonable)
rund (round)
ryddig (tidy)
sannsynlig (likely)
selvsikker (confident)
sint (angry)
skarp (sharp)
skikkelig (proper)
skyldig (guilty)
smal (narrow)
søt (sweet)
spennende (exciting)
stille (quiet)
stolt (proud)
stram (tight)
streng (strict)
stygg (ugly)
sulten (hungry)
sunn (healthy)
synlig (visible)
tilgjengelig (avaliable)
tilstrekkelig (sufficient)
tung (heavy)
tynn (thin)
uavhengig (independent)
ujevn (uneven)
ulovlig (illegal)
ulykkelig (unhappy)
umiddelbar (immediate)
urettferdig (unfair)
vellykket (successfull)
vennlig (friendly)
verdifull (valuable)
vill (wild)
villig (willing)
voksen (adult)
ærlig (honest)
åpen (open)
åpenbar (obvious)
'''